version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
