version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  backend:
    build: ./simple-blog-api  # Ensure this path points to your backend directory
    container_name: simple-blog-api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URL: mongodb+srv://smrafialam007:blogAPI@cluster0.exfov.mongodb.net/

  frontend:
    build: ./simple-blog-front  # Ensure this path points to your frontend directory
    container_name: simple-blog-front
    ports:
      - "80:80"
    depends_on:
      - backend
